#!/bin/bash
cd "${0%/*}"
OUT=../darwin
mkdir $OUT 2> /dev/null
touch $OUT/__init__.py
python3 setup.py build
DEST=lib.macosx*
DEST=$(ls -d build/${DEST} | tail -1)
cp ${DEST}/pxpcap.so .. && cp ${DEST}/pxpcap.so ${OUT}/pxpcap.so
